# Generated by Django 4.2.13 on 2024-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='book_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
